spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/practice_board
    driver-class-name: org.mariadb.jdbc.Driver
    username: testuser1
    password: dhdmswjd

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: qazwsxedc4084@gmail.com
    password: pfcpwjmrmmxcriym
    properties:
      mail:
        smtp:
          starttls:
            enable: true
#  mail:
#    host: smtp.naver.com
#    port: 465
#    username: o5eunjung@naver.com
#    password: P5U5YX2C7925
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.ssl.enable: true
#      mail.smtp.ssl.trust: smtp.naver.com
#      mail.smtp.starttls.enable: true