spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/practice_board
    driver-class-name: org.mariadb.jdbc.Driver
    username: testuser1
    password: dhdmswjd

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
